name: Update jdkdb - indices
on:
  schedule:
    - cron: '0 6 * * *'
      timezone: 'UTC'
  workflow_dispatch:
    inputs:
      allow_incomplete:
        description: 'Allow incomplete metadata files to be indexed'
        required: true
        type: boolean
        default: false
      do_commit:
        description: 'Commit the changes after creating indices'
        required: true
        type: boolean
        default: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    runs-on: 'ubuntu-latest'
    outputs:
      changes_detected: ${{ steps.auto_commit.outputs.changes_detected }}
    steps:
    - uses: actions/checkout@v6

    - name: Checkout jdkdb-data
      uses: actions/checkout@v6
      with:
        repository: jbangdev/jdkdb-data
        path: jdkdb-data

    - name: Setup JBang
      uses: jbangdev/setup-jbang@main

    - name: Run indexer manually
      if: github.event_name == 'workflow_dispatch'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        APP=https://github.com/jbangdev/jdkdb-scraper/releases/latest/download/jdkdb-scraper-standalone.jar
        EXTRA_OPTS="-m jdkdb-data/db/metadata"
        if [ "${{ inputs.allow_incomplete }}" = "true" ]; then
          EXTRA_OPTS="$EXTRA_OPTS --allow-incomplete"
        fi
        echo "Running indexer with: $EXTRA_OPTS"
        jbang --java 21+ $APP --version
        jbang --java 21+ $APP index $EXTRA_OPTS

    - name: Run indexer on schedule
      if: github.event_name == 'schedule'
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        APP=https://github.com/jbangdev/jdkdb-scraper/releases/latest/download/jdkdb-scraper-standalone.jar
        EXTRA_OPTS="-m jdkdb-data/db/metadata"
        echo "Running indexer with: $EXTRA_OPTS"
        jbang --java 21+ $APP --version
        jbang --java 21+ $APP index $EXTRA_OPTS

    - name: Remove jdkdb-data directory
      run: rm -rf jdkdb-data

    - name: Commit & Push changes
      id: auto_commit
      uses: stefanzweifel/git-auto-commit-action@v7
      if: github.event_name == 'schedule' || inputs.do_commit
      with:
        commit_message: "Update metadata indices"

    - name: Upload log files
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: update-logs
        path: logs/**/*.log
        retention-days: 30

  deploy_pages:
    needs: update
    if: needs.update.outputs.changes_detected == 'true'
    uses: ./.github/workflows/static.yml
    permissions:
      contents: read
      pages: write
      id-token: write
